### ISSUE TITLE
Document Management System for TEKSI modules

### ISSUE THREAD

**Issue by ponceta** [teksi/Home#1]
**Type :** 
Feature

**Description :** 
Enhance QGIS document management and provide datamodel extensions for document management in TEKSI modules drinking water and wastewater. 

**Related issues :**

Documentation Document Management System 
Issue qgep: https://github.com/QGEP/docs/issues/197

**Useful links :**

Plugin : https://github.com/opengisch/qgis-document-management-system-plugin

**Related pull requests :**
QGIS implementation of relations :

Datamodel drinking water module

- [x] https://github.com/qwat/qwat-data-model/pull/344
- [x] https://github.com/qwat/qwat-data-model/pull/362

.qgs project drinking water module

- [x] https://github.com/qwat/QWAT/pull/317

.qgs project wastewater module

- [x] https://github.com/QGEP/QGEP/pull/696

**Comment by sjib** [comment]
@ponceta Where is the documentation for this?
