### ISSUE TITLE
Bug on inserting manually altitude to reach points

### ISSUE THREAD

**Issue by ponceta** [teksi/Home#37]
**Description :**
Inserting manually altitude values over default values calculated by QGIS are replaced by default values when updating any field in a form, this can cause data loss or data corruption.

**Linked Issues :**
- [ ] https://github.com/QGEP/QGEP/issues/779

**Linked Pull Requests**
- [ ] https://github.com/qgis/QGIS/pull/51836

**Comment by olivierdalang** [comment]
fixed by https://github.com/qgis/QGIS/pull/51836 (thanks @domi4484)

**Comment by ponceta** [comment]
QGIS 3.28.4-2 Work as expected! Thank you!
