### ISSUE TITLE
Glitches with decimal numbers input in the co_level field in vw_qgep_wastewater_structure

### ISSUE THREAD

**Issue by ponceta** [teksi/Home#38]
**Description :**
When editing values in the co_level attribute, there's a glitch that tends to harden its usability.

**Related issues :**
- [x] https://github.com/QGEP/QGEP/issues/749
- [x] https://github.com/qgis/QGIS/issues/50859

**Related Pull requests :**
- [x]  https://github.com/qgis/QGIS/pull/52183

**Comment by domi4484** [comment]
Reference https://github.com/QGEP/QGEP/issues/749
And upstream QGIS https://github.com/qgis/QGIS/issues/50859

**Comment by domi4484** [comment]
Pull request opened upstream: https://github.com/qgis/QGIS/pull/52183

**Comment by domi4484** [comment]
Fix was merged upstream
