### ISSUE TITLE
INTERLIS Export label positions

### ISSUE THREAD

**Issue by ponceta** [teksi/Home#4]
**Description :** 

- Add functionnality to add text classes in INTERLIS export for TEKSI wastewater module

**Related issues :**

- [ ] https://github.com/QGEP/QGEP/issues/552

**Useful links :**

**Documentation:**

**Related pull requests :**

**qgepqwatili plugin :**

- [ ] https://github.com/QGEP/qgepqwat2ili/pull/73

**Comment by olivierdalang** [comment]
(done)
