### ISSUE TITLE
Extension of SWMM Functionnality + Bugfixes

### ISSUE THREAD

**Issue by ponceta** [teksi/Home#6]
**Description :** 
Extension of SWMM Functionnality + Bugfixes

**Documentation :**
- [ ] https://qgep.github.io/docs/qgep_swmm/index.html

**Related issues :**
- [x] Extension of SWMM Functionnality
- [ ] https://github.com/QGEP/QGEP/issues/728
- [ ] https://github.com/QGEP/QGEP/issues/730
- [ ] https://github.com/QGEP/QGEP/issues/560
- [ ] https://github.com/QGEP/QGEP/issues/727
- [ ] https://github.com/QGEP/QGEP/issues/728
- [ ] https://github.com/QGEP/QGEP/issues/719
- [ ] https://github.com/QGEP/QGEP/issues/720
- [ ] https://github.com/QGEP/QGEP/issues/729
- [ ] https://github.com/QGEP/QGEP/issues/646

**Related pull requests :**

- [x] https://github.com/QGEP/datamodel/pull/190
- [x] https://github.com/QGEP/QGEP/pull/777
- [x] https://github.com/QGEP/qgepplugin/pull/72
- [x] https://github.com/QGEP/qgepplugin/commit/5048b01ab93bc29fe76c99440c34de181f8e971a

**Comment by ponceta** [comment]
@sjib @tproduit do you have the list of fixed bugs? I would be glad to have it updated.

**Comment by sjib** [comment]
@ponceta Here the list of functions and bugs fixed (copied from the pull requests description)

New Functions: 
- notify user from qgep_swmm views
- import backflow_level and hydraulic_load
- export selection
- new tool to set default coefficient of friction


Issue: https://github.com/QGEP/QGEP/issues/728
Create a layer to edit the default coefficients

Messages and warning
• Most of the message regarding computation of values (roughness, dry weather flow) are migrated in the SWMM descriptions of the objects
• Info, warnings and errors are printed in the processing interface in QGIS

Catchment redirection
• See issue https://github.com/QGEP/QGEP/issues/730 and https://github.com/QGEP/QGEP/issues/560

Reach roughness:
• See issues https://github.com/QGEP/QGEP/issues/727 and https://github.com/QGEP/QGEP/issues/728

Special structures:
• See issue https://github.com/QGEP/QGEP/issues/719
• Export pump curve
• Export tank storage curve
• Modelise prank weirs as outlet with curve

Selection
• See issue https://github.com/QGEP/QGEP/issues/720 and https://github.com/QGEP/QGEP/issues/729
• Export selected network (included secondary)

Add raingage location
• Related to issue https://github.com/QGEP/QGEP/issues/646

Solve bug with the export of land use

**Comment by ponceta** [comment]
![Image](https://user-images.githubusercontent.com/8614223/224909253-278f9169-706b-4fb5-841a-4b0a5e9b561c.png)


This is what I have when trying to create an .inp file from qgep_demo data. Looks great but I'm no SWMM user.

**Comment by ponceta** [comment]
This issue is closed since SWMM developments are over but keep track of the opened issues is necessary for any additional future developments.
